/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "ApiRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
    "EventPollFailuresTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "EventPricesTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "PriceConsumer": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Site": {
      "type": "sst.aws.TanstackStart"
      "url": string
    }
    "TicketmasterApiKey": {
      "type": "sst.Secret"
      "value": string
    }
    "WatchedEventsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}